// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file tskaigikansai/line.proto (package tskaigikansai, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tskaigikansai/line.proto.
 */
export const file_tskaigikansai_line: GenFile = /*@__PURE__*/
  fileDesc("Chh0c2thaWdpa2Fuc2FpL2xpbmUucHJvdG8SDXRza2FpZ2lrYW5zYWkiEgoEVXNlchIKCgJpZBgBIAEoCSJVChdTZW5kSGVsbG9NZXNzYWdlUmVxdWVzdBINCgV0b19pZBgBIAEoCRIrCg5tZW50aW9uZWRfdXNlchgCIAEoCzITLnRza2FpZ2lrYW5zYWkuVXNlciIaChhTZW5kSGVsbG9NZXNzYWdlUmVzcG9uc2UydAoLTGluZVNlcnZpY2USZQoQU2VuZEhlbGxvTWVzc2FnZRImLnRza2FpZ2lrYW5zYWkuU2VuZEhlbGxvTWVzc2FnZVJlcXVlc3QaJy50c2thaWdpa2Fuc2FpLlNlbmRIZWxsb01lc3NhZ2VSZXNwb25zZSIAYgZwcm90bzM");

/**
 * @generated from message tskaigikansai.User
 */
export type User = Message<"tskaigikansai.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message tskaigikansai.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_tskaigikansai_line, 0);

/**
 * @generated from message tskaigikansai.SendHelloMessageRequest
 */
export type SendHelloMessageRequest = Message<"tskaigikansai.SendHelloMessageRequest"> & {
  /**
   * @generated from field: string to_id = 1;
   */
  toId: string;

  /**
   * @generated from field: tskaigikansai.User mentioned_user = 2;
   */
  mentionedUser?: User;
};

/**
 * Describes the message tskaigikansai.SendHelloMessageRequest.
 * Use `create(SendHelloMessageRequestSchema)` to create a new message.
 */
export const SendHelloMessageRequestSchema: GenMessage<SendHelloMessageRequest> = /*@__PURE__*/
  messageDesc(file_tskaigikansai_line, 1);

/**
 * empty
 *
 * @generated from message tskaigikansai.SendHelloMessageResponse
 */
export type SendHelloMessageResponse = Message<"tskaigikansai.SendHelloMessageResponse"> & {
};

/**
 * Describes the message tskaigikansai.SendHelloMessageResponse.
 * Use `create(SendHelloMessageResponseSchema)` to create a new message.
 */
export const SendHelloMessageResponseSchema: GenMessage<SendHelloMessageResponse> = /*@__PURE__*/
  messageDesc(file_tskaigikansai_line, 2);

/**
 * @generated from service tskaigikansai.LineService
 */
export const LineService: GenService<{
  /**
   * @generated from rpc tskaigikansai.LineService.SendHelloMessage
   */
  sendHelloMessage: {
    methodKind: "unary";
    input: typeof SendHelloMessageRequestSchema;
    output: typeof SendHelloMessageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tskaigikansai_line, 0);

