// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: tskaigikansai/line.proto

package tskaigikansai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tskaigikansai_line_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tskaigikansai_line_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tskaigikansai_line_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SendHelloMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToId          string `protobuf:"bytes,1,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	MentionedUser *User  `protobuf:"bytes,2,opt,name=mentioned_user,json=mentionedUser,proto3" json:"mentioned_user,omitempty"`
}

func (x *SendHelloMessageRequest) Reset() {
	*x = SendHelloMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tskaigikansai_line_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHelloMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHelloMessageRequest) ProtoMessage() {}

func (x *SendHelloMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tskaigikansai_line_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHelloMessageRequest.ProtoReflect.Descriptor instead.
func (*SendHelloMessageRequest) Descriptor() ([]byte, []int) {
	return file_tskaigikansai_line_proto_rawDescGZIP(), []int{1}
}

func (x *SendHelloMessageRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *SendHelloMessageRequest) GetMentionedUser() *User {
	if x != nil {
		return x.MentionedUser
	}
	return nil
}

type SendHelloMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendHelloMessageResponse) Reset() {
	*x = SendHelloMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tskaigikansai_line_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHelloMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHelloMessageResponse) ProtoMessage() {}

func (x *SendHelloMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tskaigikansai_line_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHelloMessageResponse.ProtoReflect.Descriptor instead.
func (*SendHelloMessageResponse) Descriptor() ([]byte, []int) {
	return file_tskaigikansai_line_proto_rawDescGZIP(), []int{2}
}

var File_tskaigikansai_line_proto protoreflect.FileDescriptor

var file_tskaigikansai_line_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73, 0x61, 0x69, 0x2f,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x73, 0x6b, 0x61,
	0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73, 0x61, 0x69, 0x22, 0x16, 0x0a, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x6a, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x05,
	0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49,
	0x64, 0x12, 0x3a, 0x0a, 0x0e, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x73, 0x6b, 0x61,
	0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73, 0x61, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0d,
	0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x22, 0x1a, 0x0a,
	0x18, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x74, 0x0a, 0x0b, 0x4c, 0x69, 0x6e,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x2e, 0x74,
	0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73, 0x61, 0x69, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x74, 0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61,
	0x6e, 0x73, 0x61, 0x69, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0xbc, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b,
	0x61, 0x6e, 0x73, 0x61, 0x69, 0x42, 0x09, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x7a, 0x75, 0x6d, 0x69, 0x6e, 0x35, 0x32, 0x31, 0x30, 0x2d, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2d, 0x6a, 0x73, 0x78, 0x2d, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73, 0x61, 0x69, 0xa2, 0x02, 0x03, 0x54,
	0x58, 0x58, 0xaa, 0x02, 0x0d, 0x54, 0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73,
	0x61, 0x69, 0xca, 0x02, 0x0d, 0x54, 0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73,
	0x61, 0x69, 0xe2, 0x02, 0x19, 0x54, 0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73,
	0x61, 0x69, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0d, 0x54, 0x73, 0x6b, 0x61, 0x69, 0x67, 0x69, 0x6b, 0x61, 0x6e, 0x73, 0x61, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tskaigikansai_line_proto_rawDescOnce sync.Once
	file_tskaigikansai_line_proto_rawDescData = file_tskaigikansai_line_proto_rawDesc
)

func file_tskaigikansai_line_proto_rawDescGZIP() []byte {
	file_tskaigikansai_line_proto_rawDescOnce.Do(func() {
		file_tskaigikansai_line_proto_rawDescData = protoimpl.X.CompressGZIP(file_tskaigikansai_line_proto_rawDescData)
	})
	return file_tskaigikansai_line_proto_rawDescData
}

var file_tskaigikansai_line_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tskaigikansai_line_proto_goTypes = []any{
	(*User)(nil),                     // 0: tskaigikansai.User
	(*SendHelloMessageRequest)(nil),  // 1: tskaigikansai.SendHelloMessageRequest
	(*SendHelloMessageResponse)(nil), // 2: tskaigikansai.SendHelloMessageResponse
}
var file_tskaigikansai_line_proto_depIdxs = []int32{
	0, // 0: tskaigikansai.SendHelloMessageRequest.mentioned_user:type_name -> tskaigikansai.User
	1, // 1: tskaigikansai.LineService.SendHelloMessage:input_type -> tskaigikansai.SendHelloMessageRequest
	2, // 2: tskaigikansai.LineService.SendHelloMessage:output_type -> tskaigikansai.SendHelloMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tskaigikansai_line_proto_init() }
func file_tskaigikansai_line_proto_init() {
	if File_tskaigikansai_line_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tskaigikansai_line_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tskaigikansai_line_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SendHelloMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tskaigikansai_line_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SendHelloMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tskaigikansai_line_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tskaigikansai_line_proto_goTypes,
		DependencyIndexes: file_tskaigikansai_line_proto_depIdxs,
		MessageInfos:      file_tskaigikansai_line_proto_msgTypes,
	}.Build()
	File_tskaigikansai_line_proto = out.File
	file_tskaigikansai_line_proto_rawDesc = nil
	file_tskaigikansai_line_proto_goTypes = nil
	file_tskaigikansai_line_proto_depIdxs = nil
}
